apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: ransdesai90/task:latest
        ports:
        - containerPort: 3000
        requests:
          cpu: 50m
          memory: 100Mi